apiVersion: apps/v1
kind: Deployment
metadata:
  creationTimestamp: null
  name: devfile-sample-3nir
spec:
  replicas: 1
  selector: {}
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
    spec:
      containers:
      - image: quay.io/pmacik-testing/tkrw-pr712-0075-0003-tenant/tkrw-pr712-0075-0003-app/devfile-sample-3nir@sha256:1dfa5832bf5a53c932ac264a9203783741992ffbe0e0fed2ce68100e4c7c3478
        name: my-nodejs
        resources: {}
status: {}
